-- =============================================================================
-- Afnon — order to table, and dish comments.
-- Run ONCE in the Supabase SQL Editor. Safe to re-run (if not exists / drop
-- constraint if exists). Until it has run, the website keeps working exactly as
-- before: /t/[token] stays a feedback page and dishes show no comment box.
-- =============================================================================
begin;


-- A. ORDER TO TABLE ------------------------------------------------------------

alter table public.orders
  add column if not exists table_id bigint references public.restaurant_tables (id) on delete restrict,
  add column if not exists table_number text;

-- The table's number is copied onto the order when it is placed, so renaming or
-- re-numbering a table later never rewrites what staff saw at the time.
alter table public.orders drop constraint if exists orders_table_number_check;
alter table public.orders add constraint orders_table_number_check
  check (table_number is null or char_length(btrim(table_number)) between 1 and 20);

-- A third way to receive an order: 'table'.
alter table public.orders drop constraint if exists orders_fulfillment_type_check;
alter table public.orders add constraint orders_fulfillment_type_check
  check (fulfillment_type in ('delivery', 'pickup', 'table'));

-- A table order always names its table (id AND number); no other order has either.
alter table public.orders drop constraint if exists orders_table_consistency;
alter table public.orders add constraint orders_table_consistency check (
  (fulfillment_type = 'table' and table_id is not null and table_number is not null)
  or (fulfillment_type <> 'table' and table_id is null and table_number is null)
);

-- A phone number is still required for delivery and pickup, but a table order is
-- placed from the table itself and needs none. When given, it stays +998XXXXXXXXX.
alter table public.orders alter column phone drop not null;
alter table public.orders drop constraint if exists orders_phone_format;
alter table public.orders add constraint orders_phone_format
  check (phone is null or phone ~ '^\+998[0-9]{9}$');
alter table public.orders drop constraint if exists orders_phone_required;
alter table public.orders add constraint orders_phone_required
  check (fulfillment_type = 'table' or phone is not null);

create index if not exists orders_table_created_idx
  on public.orders (table_id, created_at desc) where table_id is not null;


-- B. DISH COMMENTS -------------------------------------------------------------
-- The star rating itself still lives in dish_ratings (one per device per dish,
-- the source of every average). A row here is the optional words that go with a
-- rating: free text and/or one-tap reasons, with an optional name and phone.

create table if not exists public.dish_comments (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  menu_item_id bigint not null references public.menu_items (id) on delete cascade,
  -- the stars given with this comment, kept so the comment reads "★★ Too salty"
  rating       int not null check (rating between 1 and 5),
  comment      text check (comment is null or char_length(comment) <= 1000),
  -- keys such as 'too_salty' / 'great_taste', checked against a fixed list by the server
  reasons      text[] not null default '{}' check (cardinality(reasons) <= 6),
  author_name  text check (author_name is null or char_length(author_name) <= 60),
  -- private: shown to staff only, never to the public
  author_phone text check (author_phone is null or char_length(author_phone) <= 32),
  device_id    text check (device_id is null or char_length(device_id) between 16 and 64),
  visitor_key  text check (visitor_key is null or char_length(visitor_key) <= 64),
  -- Staff "Hide": instantly off the public page, reversible; deleted for good only from the Hidden list.
  is_hidden    boolean not null default false,
  hidden_at    timestamptz,
  -- a comment has words or reasons; a bare star rating is stored in dish_ratings only
  constraint dish_comments_not_empty
    check (nullif(btrim(comment), '') is not null or cardinality(reasons) > 0)
);

create index if not exists dish_comments_public_idx on public.dish_comments (menu_item_id, created_at desc) where not is_hidden;
create index if not exists dish_comments_state_idx  on public.dish_comments (is_hidden, created_at desc);
create index if not exists dish_comments_visitor_idx on public.dish_comments (visitor_key, created_at desc);
create index if not exists dish_comments_device_idx  on public.dish_comments (device_id, created_at desc);

-- No anon access of any kind (a phone number lives in this table). The website
-- reads public comments through a server action that selects only safe columns.
alter table public.dish_comments enable row level security;
revoke all on table public.dish_comments from anon, authenticated;
grant all on table public.dish_comments to service_role;

commit;
